// Copies only the models the scene uses from design/assets into public/models, plus each kit's colormap.
// Run: npm run copy:models
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = join(root, 'design', 'assets')
const dst = join(root, 'public', 'models')

// import the placement table through a tiny TS-free copy of the list to avoid a build step here:
// the allowlist is regenerated by `npm run test:run` (route.test.ts writes nothing, it only checks) so keep this in sync.
const used = (await import('./used-models.json', { with: { type: 'json' } })).default

rmSync(dst, { recursive: true, force: true })
let bytes = 0
const kits = new Set()
for (const rel of used) {
  const from = join(src, rel + '.glb')
  if (!existsSync(from)) throw new Error(`missing model ${from}`)
  const to = join(dst, rel + '.glb')
  mkdirSync(dirname(to), { recursive: true })
  copyFileSync(from, to)
  bytes += statSync(to).size
  kits.add(rel.split('/')[0])
}
for (const kit of kits) {
  const tex = join(src, kit, 'Textures', 'colormap.png')
  if (existsSync(tex)) {
    mkdirSync(join(dst, kit, 'Textures'), { recursive: true })
    copyFileSync(tex, join(dst, kit, 'Textures', 'colormap.png'))
    bytes += statSync(tex).size
  }
}
const count = readdirSync(dst, { recursive: true }).filter((f) => String(f).endsWith('.glb')).length
console.log(`copied ${count} models from ${kits.size} kits, ${(bytes / 1024 / 1024).toFixed(2)} MB`)
